### PR TITLE
Fix todolist storage bugs

### LINKED ISSUE #393: Todolist : Fix storage bugs

### PR DESCRIPTION
**Pull request by davidcaiqifan**
Fixes #393

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonAdaptedTask.java [hunk 1]
```diff
@@ -28,28 +36,23 @@
...
-        /*
-        if (source.getTag() == null) {
-            tag = null;
-        } else {
-            tag = new JsonAdaptedTag(source.getTag().get());
-        }
-        */
         if (source.getPriority().get() == null) {
             priority = null;
         } else {
```
Comment (michael-setia) [inline src/main/java/seedu/address/storage/JsonAdaptedTask.java:58]: I think we should use `isEmpty()` method for the if statement i.e. `source.getPriority().get().isEmpty()`. This is because `get()` method from an empty Optional will not return a `null` but instead throw a `NoSuchElementException`.

**Review by michael-setia — CHANGES_REQUESTED** [review]
LGTM but some small part of the code should be changed.

**Review by michael-setia — APPROVED** [review]
LGTM.
