### PR TITLE
Bugfix : Module Tracker regression bugs

### LINKED ISSUE #656: Bug : Fix regression bugs for module tracker
Bugs : 
- CRUD commands not working after switching between archive module view and regular module view
- editmodule command allowing for first tag parameter to be empty

### PR DESCRIPTION
**Pull request by davidcaiqifan**
Fixes #656

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java [hunk 1]
```diff
@@ -95,7 +75,10 @@ public EditModuleCommand parse(String args) throws ParseException {
         if (tags.isEmpty()) {
             return Optional.empty();
         }
-        Collection<String> tagSet = tags.size() == 1 && tags.contains("") ? Collections.emptySet() : tags;
```
Comment (davidcaiqifan) [inline src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java:98]: Request feedback :
Not sure of the purpose of this if else statement, but it causes editmodule to accept the first tag even if its empty e.g
editmodule t/. I have modified it such that having this condition will throw an exception,  if there are no regression bugs then it should be fine. Main issue is whether this if else statement serves any other purpose.

Comment (jonasngs) [reply src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java:98]: If I am not wrong the intended purpose of the command `editmodule t/` is to allow users to delete all their tags? The rationale is that since tag is an optional field, users should be able to delete them.

Comment (davidcaiqifan) [reply src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java:98]: Okay noted. If that is the case then we should note it down in the userguide as well.

Comment (jonasngs) [reply src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java:98]: Yes, it is in the user guide already.

**Review by jonasngs — APPROVED** [review]
LGTM.
