### PR TITLE
Fix for edit module inconsistency

### LINKED ISSUE #406: Update Editmodule test to use index

### PR DESCRIPTION
**Pull request by murtubak**
fixes #406 
also refactored out editmoduledescriptor to be in line with the rest of the code.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java [hunk 1]
```diff
@@ -34,12 +36,17 @@
...
         ArgumentMultimap argMultimap = tokenizer.tokenize();
 
-        String moduleName;
-        moduleName = argMultimap.getValue(PREFIX_EDIT_NAME).get();
+        try {
+            index = ParserUtil.parseIndex(argMultimap.getPreamble());
+        } catch (ParseException pe) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                    EditTaskCommand.MESSAGE_USAGE), pe);
+        }
```
Comment (michael-setia) [inline src/main/java/seedu/address/logic/parser/modulelistparsers/EditModuleParser.java:49]: Yup, this part should fix the index checking problem.

**Review by michael-setia — APPROVED** [review]
LGTM.
