### PR TITLE
Bug: Fix blank module lesson argument when adding a zoom link to a module and missing whitespaces in message constraints

### LINKED ISSUE #521: [PE-D] Able to add zoom links with no name
> addmodule n/CS2103T
> addzoom 1 n/ z/https://nus-sg.zoom.us/empty
Added Zoom Link: https://nus-sg.zoom.us/empty

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kaitlynng/ped#2

### LINKED ISSUE #529: [PE-D] Incorrect usage example of command shown
I wa unable to execute the command given in this example usage of add zoom.
There seems to be a typo where it should be: addzoom 1 n/lecture z/https://nus-sg.zoom.us/...

Also, in the example usage in your group's GUI, you should add the reminder that only zoom links that start with https://nus-sg.zoom.us/ is accepted. I had to go back to the User Guide to find out what was wrong.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: iqbxl/ped#4

### LINKED ISSUE #540: Bug: Fix issue where module lesson can be empty and missing whitespaces in AddZoomLinkCommand message constraints
The issue relates the the following bugs reported during the PE dry run:
 * #521 
 * #529

**Problem:** 
 * Users can enter a blank lesson name when adding a zoom link to module.
 * Missing whitespace in the message constraints of the `AddZoomLinkCommand` class.

The bug was confirmed and can be reproduced by @jonasngs 

**Cause of the bug:**
 * No checks on the lesson name argument provided  by users were conducted and hence there was no way to ascertain their  
    validity.

**Proposed changes to resolve bugs:** 
 * Implement a new `ModuleLesson`  class to encapsulate details of the module lesson which the newly added `ZoomLink` 
    belongs to. This can facilitate the validation of arguments provided.
 * Add missing whitespaces in message constraints in the `AddZoomLinkCommand` class.

### PR DESCRIPTION
**Pull request by jonasngs**
This PR:
 * Fixes #521 (PE dry run)
 * Fixes #529 (PE dry run)
 * Fixes #540 

Details of the bug can be found at: #540 

The current hashmap for ZoomLink storage maps a String, containing the module lesson which the zoom link belongs to, to the ZoomLink object.

This makes it difficult to perform checks on the module lesson argument
provided by users to validate them.

Let's
 * Create a new ModuleLesson class to encapsulate details and methods
   relating to a module lesson
 * Modify the hashmap into a hashmap that maps a ModuleLesson object to
   the corresponding zoom link
 * Modify the AddZoomLinkCommand and AddZoomLinkParser accordingly

### CODE REVIEW

File: src/main/java/seedu/address/model/contact/ContactComparatorByName.java [hunk 1]
```diff
@@ -17,7 +17,7 @@
      */
     @Override
     public int compare(Contact contact, Contact otherContact) {
-        int value = contact.getName().fullName.compareToIgnoreCase(otherContact.getName().fullName);
+        int value = contact.getName().getName().compareToIgnoreCase(otherContact.getName().getName());
         if (value > 0) {
```
Comment (michael-setia) [inline src/main/java/seedu/address/model/contact/ContactComparatorByName.java:21]: As discussed beofore, are we going to remove `Contact#getName()` and use `Contact#toString()` instead?

File: src/main/java/seedu/address/model/module/ModuleLesson.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+     * The first character of the address must not be a whitespace,
+     * otherwise " " (a blank string) becomes a valid input.
+     */
+    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} ]*";
+
+    private final String lessonName;
+
+    /**
+     * Creates and initialises a new {@code Lesson} object with a {@code lessonName}.
+     *
```
Comment (michael-setia) [inline src/main/java/seedu/address/model/module/ModuleLesson.java:25]: I think `Lesson` should be `ModuleLesson`?

File: src/main/java/seedu/address/model/module/ModuleLesson.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+     * @param lessonName String containing the lesson name.
+     */
+    public ModuleLesson(String lessonName) {
+        requireNonNull(lessonName);
+        checkArgument(isValidLesson(lessonName), MESSAGE_CONSTRAINTS);
+        this.lessonName = lessonName;
```
Comment (michael-setia) [inline src/main/java/seedu/address/model/module/ModuleLesson.java:31]: Just want to clarify, should we do `checkArgument()` for every constructor? Because if so, I will update some of my code to include this check to maintain consistency 😅

File: src/main/java/seedu/address/model/module/ModuleLesson.java [hunk 4]
```diff
@@ -0,0 +1,60 @@
+package seedu.address.model.module;
+
+import static java.util.Objects.requireNonNull;
+import static seedu.address.commons.util.AppUtil.checkArgument;
+
+/**
+ * Represents a lesson of a module.
+ * Guarantees: immutable; is valid as declared in {@link #isValidLesson(String)}
+ */
```
Comment (michael-setia) [inline src/main/java/seedu/address/model/module/ModuleLesson.java:9]: I think we should also explain that this class only represents the name of a lesson of a module? Since it can be misinterpreted to store the whole information of the lesson ?

**Review by michael-setia — APPROVED** [review]
Codes are neat and consistent. Overall, LGTM.

File: src/main/java/seedu/address/model/contact/ContactComparatorByName.java (hunk 1 above)
Comment (jonasngs) [reply src/main/java/seedu/address/model/contact/ContactComparatorByName.java:21]: Yes, this will be modified in a separate PR.

File: src/main/java/seedu/address/model/module/ModuleLesson.java (hunk 2 above)
Comment (jonasngs) [reply src/main/java/seedu/address/model/module/ModuleLesson.java:25]: Yes, it should be. Thanks for the note.

File: src/main/java/seedu/address/model/module/ModuleLesson.java (hunk 3 above)
Comment (jonasngs) [reply src/main/java/seedu/address/model/module/ModuleLesson.java:31]: Yes, I think we can do it since its good practice of defensive coding.

File: src/main/java/seedu/address/model/module/ModuleLesson.java (hunk 4 above)
Comment (jonasngs) [reply src/main/java/seedu/address/model/module/ModuleLesson.java:9]: Yes, I think we should. Thanks for the note!
